brew "chezmoi"
brew "dockutil"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "micro"
brew "mosh"
brew "python@3.13"
brew "ssh-copy-id"
brew "starship"
brew "synergy-core"
brew "tailscale"
brew "tmux"
brew "zoxide"
cask "betterdisplay"
cask "bitwarden"
cask "claude"
cask "discord"
cask "ghostty"
cask "grandperspective"
cask "hush"
cask "localsend"
cask "obsidian"
cask "qbittorrent"
cask "zed"
cask "zen"
go "tailscale.com/cmd/tailscale"
go "tailscale.com/cmd/tailscaled"
# Mac App Store apps (install manually - mas requires re-auth per app)
# mas "Amphetamine", id: 937984704
# mas "Apple Developer", id: 640199958
# mas "TestFlight", id: 899247664
# mas "Xcode", id: 497799835
